# Generated by Django 3.0.4 on 2020-03-09 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200309_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventions',
            name='date_intervention',
            field=models.DateField(default=datetime.datetime(2020, 3, 9, 18, 53, 59, 484294)),
        ),
    ]
