# Generated by Django 3.0.4 on 2020-03-09 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_interventions_date_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventions',
            name='date_intervention',
            field=models.DateField(default=datetime.datetime(2020, 3, 9, 19, 11, 32, 719045)),
        ),
    ]
