# Generated by Django 3.0.4 on 2020-03-10 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200309_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventions',
            name='date_intervention',
            field=models.DateField(default=datetime.datetime(2020, 3, 10, 8, 27, 22, 357323)),
        ),
    ]
