# Generated by Django 3.0.4 on 2020-03-11 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200310_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventions',
            name='statut',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='interventions',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 11, 11, 20, 50, 238453)),
        ),
        migrations.AlterField(
            model_name='interventions',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='interventions',
            name='intervenant',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='interventions',
            name='lieu',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
